version: "3.8"
services:
  crawler:
    container_name: crawler-service
    image: du-crawler:${CRAWLER_VER}
    build:
      context: .
      dockerfile: ./crawler/Dockerfile
    #ports:
    #  - ":"
    env_file:
      - .env
  database:
    container_name: database
    image: postgres:14.2
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data
