[package]
name = "logger"
version = "0.0.1"
edition = "2021"

[lib]
# crate-type = ["rlib", "dylib", "cdylib", "staticlib"]
name = "logger"
path = "src/lib.rs"

[dependencies]
log = "0.4"
chrono = "0.4.19"
